Repository KratosMultiphysics/Kratos, pull requests merged in 2022-04, with the labels that each got.

#9812 [Core] Core QR decomposition (from AMGCL) API
  kratos/tests/cpp_tests/utilities/test_dense_householder_qr_decomposition.cpp
  kratos/utilities/dense_householder_qr_decomposition.h
Labels: Duplicate, Kratos Core, Update API

#9806 [dem] a bit of cleanup of the DEM and SDEM tests. Introducing new style which avoids double derivation
  applications/DEMApplication/python_scripts/DEM_analysis_stage.py
  applications/DEMApplication/python_scripts/DEM_procedures.py
  applications/DEMApplication/python_scripts/cluster_file_reader.py
  applications/DEMApplication/python_scripts/sphere_strategy.py
  applications/DEMApplication/python_scripts/time_step_testing_stage.py
  applications/DEMApplication/tests/DEM2D_inlet_tests_files/ProjectParametersDEM.json
  applications/DEMApplication/tests/auxiliary_functions_for_tests.py
  applications/DEMApplication/tests/cluster_tests_files/ProjectParametersDEM2.json
  applications/DEMApplication/tests/compound_law_tests_files/compound_law_testDEM.mdpa
  applications/DEMApplication/tests/test_DEM_2D.py
  applications/DEMApplication/tests/test_DEM_2D_contact.py
  applications/DEMApplication/tests/test_DEM_2D_control_module.py
  applications/DEMApplication/tests/test_DEM_2D_inlet.py
  applications/DEMApplication/tests/test_DEM_2D_restitution.py
  applications/DEMApplication/tests/test_DEM_3D_contact.py
  applications/DEMApplication/tests/test_DEM_3D_continuum.py
  applications/DEMApplication/tests/test_DEM_3D_continuum_vs_discontinuum.py
  applications/DEMApplication/tests/test_DEM_3D_continuum_vs_wall.py
  applications/DEMApplication/tests/test_DEM_3D_inlet.py
  applications/DEMApplication/tests/test_DEM_3D_restitution.py
  applications/DEMApplication/tests/test_DEM_schemes.py
  applications/DEMApplication/tests/test_DEM_search_flags.py
  applications/DEMApplication/tests/test_DEM_search_tolerance.py
  applications/DEMApplication/tests/test_analytics.py
  applications/DEMApplication/tests/test_clusters.py
  applications/DEMApplication/tests/test_compound_law.py
  applications/DEMApplication/tests/test_constitutive_laws.py
  applications/DEMApplication/tests/test_erase_particles.py
  applications/DEMApplication/tests/test_forces_and_moments.py
  applications/DEMApplication/tests/test_friction_decay.py
  applications/DEMApplication/tests/test_glued_particles.py
  applications/DEMApplication/tests/test_history_dependent_CLs.py
  applications/DEMApplication/tests/test_inlet.py
  applications/DEMApplication/tests/test_kinematic_constraints.py
  applications/DEMApplication/tests/test_post_process.py
  applications/SwimmingDEMApplication/python_scripts/cellular_flow/cellular_flow_derivative_recovery_errors.py
  applications/SwimmingDEMApplication/python_scripts/navier_stokes_solver_vms_monolithic_DEMCoupled.py
  applications/SwimmingDEMApplication/python_scripts/swimming_DEM_analysis.py
  applications/SwimmingDEMApplication/python_scripts/swimming_DEM_solver.py
Labels: Cleanup, Python, Testing

#9825 [StructuralMechanics] Fix segfaults on empty model parts in ExplicitCentralDifferencesScheme
  applications/StructuralMechanicsApplication/custom_strategies/custom_schemes/explicit_central_differences_scheme.hpp
  applications/StructuralMechanicsApplication/custom_strategies/custom_strategies/mechanical_explicit_strategy.hpp
Labels: Applications

#9821 [HDF5Application] Remove repeated mocking
  applications/HDF5Application/tests/test_hdf5_processes.py
Labels: Applications, Python, Testing, FastPR

#9827 [StructuralMechanics] Parallel utilities in ExplicitCentralDifferencesScheme
  applications/StructuralMechanicsApplication/custom_strategies/custom_schemes/explicit_central_differences_scheme.hpp
  applications/StructuralMechanicsApplication/custom_strategies/custom_strategies/mechanical_explicit_strategy.hpp
Labels: Applications, Parallel-SMP

#9817 [Core] Specifying the return type on add_distributed_sparse_matrices_to_python
  kratos/mpi/python/add_distributed_sparse_matrices_to_python.cpp
Labels: Bugfix

#9813 [FastPR][Core][FSI] Remove old qr_utilities.h
  applications/FSIApplication/custom_utilities/ibqn_mvqn_convergence_accelerator.h
  applications/FSIApplication/custom_utilities/mvqn_recursive_convergence_accelerator.hpp
  kratos/utilities/qr_utility.h
Labels: Applications, FastPR

#9823 [LinearSolvers] Eigen inplace QR decompositions and optimization
  applications/FSIApplication/custom_utilities/mvqn_randomized_svd_convergence_accelerator.h
  applications/LinearSolversApplication/custom_decompositions/eigen_dense_column_pivoting_householder_qr_decomposition.h
  applications/LinearSolversApplication/custom_decompositions/eigen_dense_householder_qr_decomposition.h
  applications/LinearSolversApplication/custom_python/add_custom_decompositions_to_python.cpp
  applications/LinearSolversApplication/tests/test_eigen_dense_decompositions.py
Labels: Applications, Performance, Memory saving, Usability

#9796 NightlyBuilds Reschedule
  .github/workflows/ci.yml
  .github/workflows/intel_configure.sh
  .github/workflows/nightly_build.yml
  applications/CoSimulationApplication/tests/co_simulation_test_factory.py
  applications/CoSimulationApplication/tests/test_CoSimulationApplication.py
  applications/ConvectionDiffusionApplication/tests/test_ConvectionDiffusionApplication.py
  applications/DEMApplication/tests/test_DEM_search_tolerance.py
  applications/FluidDynamicsApplication/tests/test_FluidDynamicsApplication.py
  applications/IgaApplication/tests/test_IgaApplication.py
  applications/MeshMovingApplication/tests/test_MeshMovingApplication.py
  applications/MultilevelMonteCarloApplication/tests/test_MultilevelMonteCarloApplication.py
  applications/ShapeOptimizationApplication/tests/shape_optimization_test_factory.py
  applications/ShapeOptimizationApplication/tests/test_ShapeOptimizationApplication.py
  applications/StructuralMechanicsApplication/tests/test_StructuralMechanicsApplication.py
  kratos/python_scripts/KratosUnittest.py
  kratos/tests/test_KratosCore.py
Labels: Continuous Integration

#9838 [Core] Improving CSR interface and low overhead conversion to PETSc
  kratos/mpi/python/add_distributed_sparse_matrices_to_python.cpp
  kratos/python/add_sparse_matrices_to_python.cpp
  kratos/python_scripts/petsc_conversion_tools.py
Labels: Kratos Core, Python, Feature

#9781 [Core] Non-historical and custom variable normal
  applications/ContactStructuralMechanicsApplication/custom_processes/base_contact_search_process.cpp
  applications/ContactStructuralMechanicsApplication/custom_processes/normal_check_process.cpp
  applications/ContactStructuralMechanicsApplication/custom_strategies/custom_convergencecriterias/base_mortar_criteria.h
  applications/ContactStructuralMechanicsApplication/tests/cpp_tests/test_search_process.cpp
  applications/ContactStructuralMechanicsApplication/tests/cpp_tests/test_weighted_gap.cpp
  applications/FluidDynamicsApplication/custom_processes/apply_compressible_navier_stokes_boundary_conditions_process.cpp
  applications/StructuralMechanicsApplication/custom_utilities/perturb_geometry_base_utility.cpp
  applications/StructuralMechanicsApplication/tests/cpp_tests/test_shell_to_solid_shell_process.cpp
  kratos/processes/simple_mortar_mapper_process.cpp
  kratos/python/add_geometrical_utilities_to_python.cpp
  kratos/tests/cpp_tests/processes/test_mortar_mapper_process.cpp
  kratos/tests/test_normal_utils.py
  kratos/utilities/mortar_utilities.cpp
  kratos/utilities/normal_calculation_utils.cpp
  kratos/utilities/normal_calculation_utils.h
Labels: Enhancement, Kratos Core

#9840 [FastPR][Leftover] Embedded FSI solver leftover
  applications/FSIApplication/python_scripts/partitioned_embedded_fsi_base_solver.py
Labels: FastPR, Leftover

#9848 [PfemFluid] new remeshing and material property settings for two-fluid analysis
  applications/DelaunayMeshingApplication/custom_utilities/mesh_data_transfer_utilities.cpp
  applications/PfemFluidDynamicsApplication/custom_elements/two_step_updated_lagrangian_V_P_implicit_fluid_PSPG_element.cpp
  applications/PfemFluidDynamicsApplication/custom_processes/generate_new_nodes_before_meshing_process.hpp
  applications/PfemFluidDynamicsApplication/custom_processes/remove_mesh_nodes_for_fluids_process.hpp
  applications/PfemFluidDynamicsApplication/custom_processes/set_material_properties_from_fluid_to_rigid_nodes_process.hpp
  applications/PfemFluidDynamicsApplication/custom_processes/set_material_properties_to_fluid_nodes_process.hpp
  applications/PfemFluidDynamicsApplication/tests/NightTests.py
  applications/PfemFluidDynamicsApplication/tests/SmallTests.py
  applications/PfemFluidDynamicsApplication/tests/fluid_element_tests/Test_2D_MultiFluid/PFEMFluidMaterials.json
  applications/PfemFluidDynamicsApplication/tests/fluid_element_tests/Test_2D_MultiFluid/ProjectParameters.json
  applications/PfemFluidDynamicsApplication/tests/fluid_element_tests/Test_2D_MultiFluid/Test_2D_MultiFluid.mdpa
  applications/PfemFluidDynamicsApplication/tests/fluid_element_tests/Test_2D_MultiFluid/Test_2D_MultiFluid_results.json
Labels: Enhancement, Cleanup

#9846 [Shallow] Add variable to FC limiter
  applications/ShallowWaterApplication/custom_elements/conservative_element.cpp
  applications/ShallowWaterApplication/custom_utilities/flux_limiter.h
  applications/ShallowWaterApplication/python_scripts/shallow_water_base_solver.py
  applications/ShallowWaterApplication/python_scripts/stabilized_shallow_water_solver.py
  applications/ShallowWaterApplication/tests/elements_tests/monotonic_shallow_water_2d_3n_reference.json
Labels: Enhancement

#9854 [Shallow] LineGraphOutputProcess: allow historical and nonhistorical
  applications/ShallowWaterApplication/python_scripts/postprocess/line_graph_output_process.py
Labels: Enhancement

#9853 [Parameters] Add AddStringArray
  kratos/includes/kratos_parameters.h
  kratos/python/add_kratos_parameters_to_python.cpp
  kratos/sources/kratos_parameters.cpp
  kratos/tests/test_kratos_parameters.py
Labels: Incomplete, Usability

#9630 [IGA] add output eigen values process
  applications/IgaApplication/custom_processes/output_eigen_values_process.cpp
  applications/IgaApplication/custom_processes/output_eigen_values_process.h
  applications/IgaApplication/custom_python/add_custom_processes_to_python.cpp
  applications/IgaApplication/python_scripts/output_eigen_values_process.py
Labels: Applications

#9842 [ReadMaterialsUtility] Unused mesh id
  kratos/utilities/read_materials_utility.cpp
  kratos/utilities/read_materials_utility.h
Labels: Cleanup, FastPR, Leftover

#9859 [Timer] [GidIO] PrintTimingInformation must be called once
  kratos/includes/gid_io.h
Labels: Cleanup, Logging

#9845 [Core] [Timer] Cleanup
  kratos/python/add_other_utilities_to_python.cpp
  kratos/python_scripts/timer_process.py
Labels: Cleanup, FastPR, Leftover, Minor

#9860 [Core] Moving OBB to geometries folder
  kratos/geometries/oriented_bounding_box.cpp
  kratos/geometries/oriented_bounding_box.h
  kratos/processes/find_intersected_geometrical_objects_with_obb_process.h
  kratos/tests/cpp_tests/sources/test_oriented_bounding_box.cpp
Labels: Kratos Core, FastPR, Refactor

#9861 [PfemFluid] Improvement for two fluid analysis
  applications/DelaunayMeshingApplication/custom_utilities/mesher_utilities.hpp
  applications/PfemFluidDynamicsApplication/custom_processes/generate_new_nodes_before_meshing_process.hpp
  applications/PfemFluidDynamicsApplication/custom_processes/remove_mesh_nodes_for_fluids_process.hpp
  applications/PfemFluidDynamicsApplication/tests/fluid_element_tests/Test_2D_MultiFluid/ProjectParameters.json
  applications/PfemFluidDynamicsApplication/tests/totalVolumeBeforeMeshing.txt
Labels: Enhancement, Cleanup

#9855 [CoSim] update CoSimIO to 4.1
  applications/CoSimulationApplication/custom_external_libraries/CoSimIO/co_sim_io/sources/communication/communication.cpp
Labels: Applications, External library, FastPR, Feature

#9756 Copy properties modeler
  kratos/modeler/copy_properties_modeler.cpp
  kratos/modeler/copy_properties_modeler.h
  kratos/python/add_modeler_to_python.cpp
  kratos/tests/cpp_tests/modeler/test_copy_properties_modeler.cpp
Labels: Usability

#9862 [Shallow] Visualization processes
  applications/ShallowWaterApplication/custom_python/add_custom_utilities_to_python.cpp
  applications/ShallowWaterApplication/custom_utilities/shallow_water_utilities.cpp
  applications/ShallowWaterApplication/custom_utilities/shallow_water_utilities.h
  applications/ShallowWaterApplication/python_scripts/postprocess/auxiliary_nodes_visualization_process.py
  applications/ShallowWaterApplication/python_scripts/postprocess/offset_ids_process.py
  applications/ShallowWaterApplication/python_scripts/postprocess/swap_coordinates_and_offset_ids_process.py
  applications/ShallowWaterApplication/python_scripts/postprocess/swap_coordinates_process.py
  applications/ShallowWaterApplication/python_scripts/postprocess/visualization_mesh_process.py
  applications/ShallowWaterApplication/python_scripts/testing/empty_output_process.py
  applications/ShallowWaterApplication/python_scripts/testing/empty_solver_for_testing.py
  applications/ShallowWaterApplication/tests/processes_tests/visualization_mesh_process_parameters.json
Labels: Post Process

#9866 [Fluid] Fixed formula for energy in physics-based shock captuting
  applications/FluidDynamicsApplication/custom_processes/shock_capturing_physics_based_process.h
Labels: FastPR, Bugfix

#9865 [Fluid] Fixed bug that disabled thermal sensor's contribution to artificial conductivity
  applications/FluidDynamicsApplication/custom_processes/shock_capturing_physics_based_process.cpp
  applications/FluidDynamicsApplication/tests/cpp_tests/test_shock_capturing_physics_based_process.cpp
Labels: FastPR, Bugfix

#9873 [Shallow] Add check for benchmarking utilities
  applications/ShallowWaterApplication/python_scripts/benchmarks/base_benchmark_process.py
  applications/ShallowWaterApplication/python_scripts/postprocess/convergence_output_process.py
Labels: Benchmarking, Usability
