Repository KratosMultiphysics/Kratos, pull requests merged in 2022-07, with the labels that each got.

#9993 [FreeSurface] Fix initialization warnings
  applications/FreeSurfaceApplication/custom_utilities/edge_data.h
  applications/FreeSurfaceApplication/custom_utilities/edge_data_c2c.h
Labels: Warning

#10001 Add link to guidelines for MPI compilation
  INSTALL.md
  applications/MetisApplication/README.md
  applications/TrilinosApplication/README.md
Labels: Documentation

#10015 [FastPR][ConsLaws] Minor fix in NeoHookean postprocess
  applications/ConstitutiveLawsApplication/custom_constitutive/hyper_elastic_isotropic_neo_hookean_3d.cpp
  applications/ConstitutiveLawsApplication/custom_constitutive/hyper_elastic_isotropic_neo_hookean_plane_strain_2d.cpp
Labels: Applications, FastPR, Bugfix

#9939 [Core][AutomaticDiff] Support for 4th order tensors
  kratos/python_scripts/sympy_fe_utilities.py
  kratos/tests/test_sympy_fe_utilities.py
Labels: Kratos Core, Feature

#10026 [Core] fix generic find elements neighbors in mpi
  kratos/processes/generic_find_elements_neighbours_process.cpp
  kratos/processes/generic_find_elements_neighbours_process.h
Labels: Parallel-MPI, Bugfix

#10022 [FastPR][Core] Minor improvement in automatic differentiation utilities
  kratos/python_scripts/sympy_fe_utilities.py
Labels: Enhancement, Kratos Core, FastPR

#10014 Testing shape functions second derivatives
  kratos/utilities/geometry_tester.cpp
  kratos/utilities/geometry_tester.h
Labels: Testing

#10027 [Shallow] Python scripts cleanup
  applications/ShallowWaterApplication/python_scripts/benchmarks/dam_break_benchmark.py
  applications/ShallowWaterApplication/python_scripts/benchmarks/dry_dam_break_benchmark.py
  applications/ShallowWaterApplication/python_scripts/modelers/dry_dam_break_modeler.py
  applications/ShallowWaterApplication/python_scripts/postprocess/swap_coordinates_process.py
  applications/ShallowWaterApplication/tests/processes_tests/dry_dam_break_benchmark_parameters.json
Labels: Cleanup

#10035 [Core] Adding missing Access methods to PointerVectorMap
  kratos/containers/pointer_vector_map.h
Labels: Kratos Core, FastPR, Minor

#10024 [Core][CMake] Adding error if Boost is not found
  CMakeLists.txt
Labels: Kratos Core, Compilation, FastPR, CMake

#10033 Updated the CODEOWNERS github file to point to kratos geomechanics team
  .github/CODEOWNERS
Labels: FastPR, GeoMechanics

#10039 [Github] TODO list wrongly defined
  .github/ISSUE_TEMPLATE/todo.md
Labels: Kratos Core, Documentation, FastPR

#10038 [Core] Adding missing Access methods to PointerVectorSet
  kratos/containers/pointer_vector_map.h
  kratos/containers/pointer_vector_set.h
Labels: Kratos Core, Incomplete, FastPR, Inconsistent, Minor

#10046 [FluidBio] Parabolic inlet improvements
  applications/FluidDynamicsBiomedicalApplication/custom_python/add_custom_utilities_to_python.cpp
  applications/FluidDynamicsBiomedicalApplication/custom_utilities/parabolic_profile_utilities.cpp
  applications/FluidDynamicsBiomedicalApplication/custom_utilities/parabolic_profile_utilities.h
  applications/FluidDynamicsBiomedicalApplication/python_scripts/apply_parabolic_inlet_process.py
  applications/FluidDynamicsBiomedicalApplication/tests/apply_parabolic_inlet_process_test.py
Labels: Enhancement, Applications

#10051 [CI] Using alternative link for Boost
  .github/workflows/ci.yml
Labels: FastPR, Continuous Integration

#10053 [LinearSolversApplication] Update last version of MKL
  applications/LinearSolversApplication/README.md
Labels: Applications, Documentation, FastPR

#9816 [CoSim] Add MPM DEM coupling
  applications/CoSimulationApplication/python_scripts/solver_wrappers/kratos/particle_mechanics_dirichlet_wrapper.py
  applications/CoSimulationApplication/python_scripts/solver_wrappers/kratos/particle_mechanics_neumann_wrapper.py
  applications/CoSimulationApplication/tests/co_simulation_test_factory.py
  applications/CoSimulationApplication/tests/mpm_dem/MaterialsDEM.json
  applications/CoSimulationApplication/tests/mpm_dem/ParticleMaterials.json
  applications/CoSimulationApplication/tests/mpm_dem/ProjectParametersDEM.json
  applications/CoSimulationApplication/tests/mpm_dem/ProjectParametersMPM.json
  applications/CoSimulationApplication/tests/mpm_dem/beam_Body.mdpa
  applications/CoSimulationApplication/tests/mpm_dem/beam_Grid.mdpa
  applications/CoSimulationApplication/tests/mpm_dem/cosim_mpm_dem_parameters.json
  applications/CoSimulationApplication/tests/mpm_dem/cosim_mpm_dem_results.json
  applications/CoSimulationApplication/tests/mpm_dem/dempartDEM.mdpa
  applications/CoSimulationApplication/tests/mpm_dem/dempartDEM_FEM_boundary.mdpa
  applications/CoSimulationApplication/tests/mpm_dem/dempartDEM_Inlet.mdpa
  applications/CoSimulationApplication/tests/mpm_fem_beam/ProjectParametersMPM.json
  applications/CoSimulationApplication/tests/mpm_fem_beam/cosim_mpm_fem_beam_parameters.json
  applications/ParticleMechanicsApplication/custom_conditions/particle_based_conditions/mpm_particle_base_condition.cpp
  applications/ParticleMechanicsApplication/custom_conditions/particle_based_conditions/mpm_particle_base_condition.h
  applications/ParticleMechanicsApplication/custom_conditions/particle_based_conditions/mpm_particle_base_dirichlet_condition.cpp
  applications/ParticleMechanicsApplication/custom_conditions/particle_based_conditions/mpm_particle_base_dirichlet_condition.h
  applications/ParticleMechanicsApplication/custom_conditions/particle_based_conditions/mpm_particle_point_load_condition.cpp
  applications/ParticleMechanicsApplication/custom_conditions/particle_based_conditions/mpm_particle_point_load_condition.h
  applications/ParticleMechanicsApplication/custom_python/particle_mechanics_python_application.cpp
  applications/ParticleMechanicsApplication/custom_utilities/mpm_particle_generator_utility.cpp
  applications/ParticleMechanicsApplication/particle_mechanics_application.cpp
  applications/ParticleMechanicsApplication/particle_mechanics_application_variables.cpp
  applications/ParticleMechanicsApplication/particle_mechanics_application_variables.h
  applications/ParticleMechanicsApplication/python_scripts/apply_mpm_coupling_interface_dirichlet_condition_process.py
  applications/ParticleMechanicsApplication/python_scripts/apply_mpm_coupling_interface_neumann_condition_process.py
Labels: Enhancement

#10057 [core] templated divide geometry utility
  applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.cpp
  kratos/modified_shape_functions/modified_shape_functions.cpp
  kratos/modified_shape_functions/modified_shape_functions.h
  kratos/modified_shape_functions/tetrahedra_3d_4_ausas_modified_shape_functions.cpp
  kratos/modified_shape_functions/tetrahedra_3d_4_ausas_modified_shape_functions.h
  kratos/modified_shape_functions/tetrahedra_3d_4_modified_shape_functions.cpp
  kratos/modified_shape_functions/tetrahedra_3d_4_modified_shape_functions.h
  kratos/modified_shape_functions/triangle_2d_3_ausas_modified_shape_functions.cpp
  kratos/modified_shape_functions/triangle_2d_3_ausas_modified_shape_functions.h
  kratos/modified_shape_functions/triangle_2d_3_modified_shape_functions.cpp
  kratos/modified_shape_functions/triangle_2d_3_modified_shape_functions.h
  kratos/tests/cpp_tests/utilities/test_divide_tetrahedra_3d_4.cpp
  kratos/tests/cpp_tests/utilities/test_divide_triangle_2d_3.cpp
  kratos/tests/cpp_tests/utilities/test_divide_triangle_3d_3.cpp
  kratos/utilities/divide_geometry.cpp
  kratos/utilities/divide_geometry.h
  kratos/utilities/divide_tetrahedra_3d_4.cpp
  kratos/utilities/divide_tetrahedra_3d_4.h
  kratos/utilities/divide_triangle_2d_3.cpp
  kratos/utilities/divide_triangle_2d_3.h
  kratos/utilities/divide_triangle_3d_3.cpp
  kratos/utilities/divide_triangle_3d_3.h
  kratos/utilities/embedded_skin_utility.cpp
  kratos/utilities/embedded_skin_utility.h
Labels: C++, API Breaker

#10056 [structural] Allow arbitrary GP collocation, stored in the elem
  applications/StructuralMechanicsApplication/custom_elements/base_solid_element.cpp
  applications/StructuralMechanicsApplication/custom_elements/base_solid_element.h
  applications/StructuralMechanicsApplication/custom_elements/small_displacement.cpp
Labels: Enhancement, Applications, C++

#10074 [BDF] Constant DT and high order schemes
  kratos/solving_strategies/schemes/residual_based_bdf_scheme.h
Labels: Bugfix
